import axiosInstance from "./axiosInstance";

export { axiosInstance };

// Central API endpoints registry
export const ENDPOINTS = {
  auth: {
    login: "/api/auth/login",
    forgotPassword: "/api/auth/forgot-password",
    resetPassword: "/api/auth/reset-password",
  },
  admin: {
    agents: "/api/admin/agents",
    agentActive: (id) => `/api/admin/agents/${id}/active`,
    agentDelete: (id) => `/api/admin/agents/${id}`,
    routingPolicy: "/api/admin/routing-policy",
    pairingCode: "/api/admin/whatsapp/pairing-code",
    verifyWhatsapp: "/api/admin/whatsapp/verify",
    metaForms: "/api/admin/meta-forms",
    verifySMTP: "/api/admin/smtp/verify",
    billingQuotas: "/api/admin/billing/quotas",
    billingInvoices: "/api/admin/billing/invoices",
    automationRules: "/api/admin/automation-rules",
    ruleStatus: (id) => `/api/admin/automation-rules/${id}/status`,
    ruleDelete: (id) => `/api/admin/automation-rules/${id}`,
  },
  // Backward compatibility alias for clientAdmin
  get clientAdmin() { return this.admin; },
  leads: {
    base: "/api/leads",
    createPublic: "/api/leads/create",
    status: (id) => `/api/leads/${id}/status`,
    notes: (id) => `/api/leads/${id}/notes`,
    followUp: (id) => `/api/leads/${id}/followup`,
  },
  chat: {
    conversations: "/api/conversations",
    messages: (leadId) => `/api/conversations/${leadId}/messages`,
    autoReply: (leadId) => `/api/conversations/${leadId}/auto-reply`,
  },
  appointments: {
    base: "/api/appointments",
    cancel: (id) => `/api/appointments/${id}/cancel`,
    confirm: (id) => `/api/appointments/${id}/confirm`,
    publicSlots: (companyId, date) => `/api/public/appointments/slots?companyId=${companyId}&date=${date}`,
    publicBook: "/api/public/appointments",
    publicMeta: (companyId) => `/api/public/appointments/meta?companyId=${companyId}`,
    slotConfigs: "/api/admin/appointments/slot-configs",
    slotConfigDelete: (id) => `/api/admin/appointments/slot-configs/${id}`,
    serviceConfigs: "/api/admin/appointments/service-configs",
    serviceConfigDelete: (id) => `/api/admin/appointments/service-configs/${id}`,
  },
  knowledge: {
    faqs: "/api/knowledge/faqs",
    faqDelete: (id) => `/api/knowledge/faqs/${id}`,
    documents: "/api/knowledge/documents",
    documentUpload: "/api/knowledge/documents/upload",
    aiSettings: "/api/knowledge/ai-settings",
    whatsappTemplates: "/api/knowledge/whatsapp-templates",
    templateDelete: (id) => `/api/knowledge/whatsapp-templates/${id}`,
  },
  webhook: {
    aiChat: "/api/ai/chat",
    whatsapp: "/api/webhooks/whatsapp",
    facebookLeads: "/api/webhooks/facebook-leads",
  },
  whatsapp: {
    contacts: "/api/admin/whatsapp/contacts",
    contactDetail: (id) => `/api/admin/whatsapp/contacts/${id}`,
    contactTags: "/api/admin/whatsapp/contacts/tags",
    contactExport: "/api/admin/whatsapp/contacts/export",
    contactBulkDelete: "/api/admin/whatsapp/contacts/bulk-delete",
    contactBulkTag: "/api/admin/whatsapp/contacts/bulk-tag",
    contactImport: "/api/admin/whatsapp/contacts/import",
    groups: "/api/admin/whatsapp/groups",
    groupDetail: (id) => `/api/admin/whatsapp/groups/${id}`,
    groupAssign: (id) => `/api/admin/whatsapp/groups/${id}/assign`,
    groupRemove: (id) => `/api/admin/whatsapp/groups/${id}/remove`,
    campaigns: "/api/admin/whatsapp/campaigns",
    campaignDetail: (id) => `/api/admin/whatsapp/campaigns/${id}`,
    campaignDuplicate: (id) => `/api/admin/whatsapp/campaigns/${id}/duplicate`,
    campaignSend: (id) => `/api/admin/whatsapp/campaigns/${id}/send`,
    campaignCancel: (id) => `/api/admin/whatsapp/campaigns/${id}/cancel`,
    campaignPause: (id) => `/api/admin/whatsapp/campaigns/${id}/pause`,
    scheduled: "/api/admin/whatsapp/scheduled",
    reportsDashboard: "/api/admin/whatsapp/reports/dashboard",
    reportsCampaigns: "/api/admin/whatsapp/reports/campaigns",
    reportsTrends: "/api/admin/whatsapp/reports/trends",
    reportsRecent: "/api/admin/whatsapp/reports/recent",
    settings: "/api/admin/whatsapp/settings",
    settingsConnect: "/api/admin/whatsapp/settings/connect",
    settingsDisconnect: "/api/admin/whatsapp/settings/disconnect",
    apiKeys: "/api/admin/whatsapp/api-keys",
    apiKeysRegenerate: "/api/admin/whatsapp/api-keys/regenerate",
    billing: "/api/admin/whatsapp/billing",
  },
};

export default axiosInstance;
